export const BRAND_MAPPING: { [key: string]: string } = {
    "1": "Polytech",
    "2": "Pobedit",
    "3": "Russia",
    "4": "Polyagro",
    "5": "Germez",
    "6": "Ekotools",
    "7": "Superpen",
    "8": "PolyagroGold",
    "9": "Guppy",
    "10": "Polytech Quality",
    "11": "PolyagroCamp",
    "12": "PolyagroLite",
    "14": "Waterley",
    "15": "JilionSP",
    "16": "JilionPT",
    "17": "PobeditMotor",
    "20": "Ekofoam",
    "21": "PobeditThor",
    "22": "PobeditThor",
    "23": "PobeditThor",
    "24": "Shahter",
    "25": "Koplich",
    "26": "Kopalovna",
    "27": "PolyagroAqua",
    "28": "Hokku",
    "29": "Severyanin",
    "30": "FuksiaM",
    "31": "TORX",
    "32": "Nordeco"
};
