export const LAYER_NAMES = {
    LIST_CONTAINER: "#ListContainer",
    TITLE: "#Title",
    DESCRIPTION: "#Description",
    DISCOUNT: "productDiscount",
    DISCOUNT_INFO: "#DiscountInfo",
    SURPRISE: "#Suprise",
    SURPRISE_WRAPPER: "surpriseWrapper",
    BOX_PRICE: "#PriceBox",
    BOX_QTY: "#QtyBox",
    BOX_NOTICE: "#BoxNotice",
    VIDEO_QR_WRAPPER: "#VideoQrWrapper",
    VIDEO_LINK: "#VideoLink",
    IMAGE: "#Image",
    LOGO: "Main Logotypes",
    ROW_SKU: "#SKU",
    ROW_SPECS: "#Specs",
    ROW_MIN: "#Min",
    ROW_QTY: "#Qty",
    ROW_PRICE: "#Price",
    ROW_ITEM_SALE: "itemSale",
    ROW_ITEM_SALE_DISCOUNT: "priceProductDiscount",
    SALE_STAR: "saleStar"
};
